/**
 * Localized strings for the PDF/AudioBook screen.
 * Pass `language` from App as a prop and call t(language, "key").
 */

const STRINGS = {
  en: {
    "controls.aiModel": "AI Model",
    "upload.title": "Upload a PDF",
    "upload.hint": "Drop a file here or click to browse",
    "upload.button": "Choose PDF",
    "upload.invalid": "Please upload a valid PDF file",
    "upload.tooLarge": "PDF must be smaller than 20 MB",
    "loading": "Loading PDF…",
    "loadError": "Could not load this PDF",
    "page": "Page",
    "of": "of",
    "zoomIn": "Zoom in",
    "zoomOut": "Zoom out",
    "prevPage": "Previous page",
    "nextPage": "Next page",
    "changeFile": "Change PDF",
    "selection.generate": "Generate audio",
    "convo.title": "Conversations",
    "convo.empty.title": "No conversations yet",
    "convo.empty.hint": "Select text in the PDF, then click \u201CGenerate audio.\u201D",
    "convo.you": "Selected text",
    "convo.assistant": "Generated speech",
    "convo.delete": "Remove",
    "convo.clearAll": "Clear all",
    "convo.generating": "Generating…",
    "convo.failed": "Failed to generate",
    "convo.retry": "Retry",
    "err.noUrl": "No audio URL received from server",
    "err.backendFailed": "Audio generation failed on backend",
    "err.timeout": "Audio generation timed out",
    "err.generic": "Failed to generate audio. Please try again.",
  },
  km: {
    "controls.aiModel": "ម៉ូដែល AI",
    "upload.title": "ផ្ទុកឯកសារ PDF",
    "upload.hint": "ទម្លាក់ឯកសារនៅទីនេះ ឬចុចដើម្បីរកមើល",
    "upload.button": "ជ្រើសរើស PDF",
    "upload.invalid": "សូមផ្ទុកឯកសារ PDF ដែលត្រឹមត្រូវ",
    "upload.tooLarge": "PDF ត្រូវតែតូចជាង 20 MB",
    "loading": "កំពុងផ្ទុក PDF…",
    "loadError": "មិនអាចផ្ទុក PDF នេះបានទេ",
    "page": "ទំព័រ",
    "of": "នៃ",
    "zoomIn": "ពង្រីក",
    "zoomOut": "បង្រួម",
    "prevPage": "ទំព័រមុន",
    "nextPage": "ទំព័របន្ទាប់",
    "changeFile": "ប្តូរ PDF",
    "selection.generate": "បង្កើតសំឡេង",
    "convo.title": "ការសន្ទនា",
    "convo.empty.title": "មិនទាន់មានការសន្ទនា",
    "convo.empty.hint": "ជ្រើសអក្សរក្នុង PDF រួចចុច \u201Cបង្កើតសំឡេង\u201D",
    "convo.you": "អក្សរដែលបានជ្រើស",
    "convo.assistant": "សំឡេងដែលបានបង្កើត",
    "convo.delete": "លុប",
    "convo.clearAll": "សម្អាតទាំងអស់",
    "convo.generating": "កំពុងបង្កើត…",
    "convo.failed": "មិនអាចបង្កើតបាន",
    "convo.retry": "ព្យាយាមម្តងទៀត",
    "err.noUrl": "មិនទទួលបាន URL សំឡេងពីម៉ាស៊ីនមេ",
    "err.backendFailed": "ការបង្កើតសំឡេងបានបរាជ័យ",
    "err.timeout": "ការបង្កើតសំឡេងលើសពេលកំណត់",
    "err.generic": "មិនអាចបង្កើតសំឡេងបានទេ សូមព្យាយាមម្តងទៀត។",
  },
  zh: {
    "controls.aiModel": "AI 模型",
    "upload.title": "上传 PDF",
    "upload.hint": "拖放文件到此处，或点击浏览",
    "upload.button": "选择 PDF",
    "upload.invalid": "请上传有效的 PDF 文件",
    "upload.tooLarge": "PDF 必须小于 20 MB",
    "loading": "正在加载 PDF…",
    "loadError": "无法加载此 PDF",
    "page": "第",
    "of": "页 / 共",
    "zoomIn": "放大",
    "zoomOut": "缩小",
    "prevPage": "上一页",
    "nextPage": "下一页",
    "changeFile": "更换 PDF",
    "selection.generate": "生成语音",
    "convo.title": "对话",
    "convo.empty.title": "暂无对话",
    "convo.empty.hint": "在 PDF 中选择文本，然后点击\u201C生成语音\u201D。",
    "convo.you": "选中的文本",
    "convo.assistant": "生成的语音",
    "convo.delete": "删除",
    "convo.clearAll": "全部清除",
    "convo.generating": "生成中…",
    "convo.failed": "生成失败",
    "convo.retry": "重试",
    "err.noUrl": "未从服务器收到音频地址",
    "err.backendFailed": "后端语音生成失败",
    "err.timeout": "语音生成超时",
    "err.generic": "语音生成失败，请重试。",
  },
  fr: {
    "controls.aiModel": "Modèle IA",
    "upload.title": "Téléverser un PDF",
    "upload.hint": "Glissez un fichier ici ou cliquez pour parcourir",
    "upload.button": "Choisir un PDF",
    "upload.invalid": "Veuillez téléverser un fichier PDF valide",
    "upload.tooLarge": "Le PDF doit faire moins de 20 Mo",
    "loading": "Chargement du PDF…",
    "loadError": "Impossible de charger ce PDF",
    "page": "Page",
    "of": "sur",
    "zoomIn": "Zoom avant",
    "zoomOut": "Zoom arrière",
    "prevPage": "Page précédente",
    "nextPage": "Page suivante",
    "changeFile": "Changer de PDF",
    "selection.generate": "Générer l\u2019audio",
    "convo.title": "Conversations",
    "convo.empty.title": "Aucune conversation",
    "convo.empty.hint": "Sélectionnez du texte dans le PDF, puis cliquez sur \u00AB Générer l\u2019audio \u00BB.",
    "convo.you": "Texte sélectionné",
    "convo.assistant": "Voix générée",
    "convo.delete": "Supprimer",
    "convo.clearAll": "Tout effacer",
    "convo.generating": "Génération…",
    "convo.failed": "Échec de la génération",
    "convo.retry": "Réessayer",
    "err.noUrl": "Aucune URL audio reçue du serveur",
    "err.backendFailed": "La génération audio a échoué côté serveur",
    "err.timeout": "Génération audio expirée",
    "err.generic": "Échec de la génération audio. Veuillez réessayer.",
  },
};

export const t = (language, key) => {
  const bundle = STRINGS[language] || STRINGS.en;
  return bundle[key] || STRINGS.en[key] || key;
};